/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '../../../../../src/app/pages/onboarding/onboarding.component';
import * as i3 from '../../../../../src/app/services/wallet/wallet.service';
const styles_OnboardingComponent:any[] = ([] as any[]);
export const RenderType_OnboardingComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_OnboardingComponent,data:{}});
export function View_OnboardingComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(1,
      16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),
      (null as any),(null as any),(null as any),(null as any))),i0.ɵdid(2,212992,(null as any),
      0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,i0.ComponentFactoryResolver,
          [8,(null as any)],i0.ChangeDetectorRef],(null as any),(null as any)),(_l()(),
      i0.ɵted(-1,(null as any),['\n  ']))],(_ck,_v) => {
    _ck(_v,2,0);
  },(null as any));
}
export function View_OnboardingComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'detail',([] as any[]),
      (null as any),(null as any),(null as any),View_OnboardingComponent_0,RenderType_OnboardingComponent)),
      i0.ɵdid(1,114688,(null as any),0,i2.OnboardingComponent,[i1.Router,i3.WalletService],
          (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const OnboardingComponentNgFactory:i0.ComponentFactory<i2.OnboardingComponent> = i0.ɵccf('detail',
    i2.OnboardingComponent,View_OnboardingComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL29uYm9hcmRpbmcvb25ib2FyZGluZy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9nZXJ0amFhcC9zb3VyY2VzL2RlY29zLmNyeXB0by5lc2lnbmF0dXJlL3NyYy9hcHAvcGFnZXMvb25ib2FyZGluZy9vbmJvYXJkaW5nLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL29uYm9hcmRpbmcvb25ib2FyZGluZy5jb21wb25lbnQudHMuT25ib2FyZGluZ0NvbXBvbmVudC5odG1sIiwibmc6Ly8vaG9tZS9nZXJ0amFhcC9zb3VyY2VzL2RlY29zLmNyeXB0by5lc2lnbmF0dXJlL3NyYy9hcHAvcGFnZXMvb25ib2FyZGluZy9vbmJvYXJkaW5nLmNvbXBvbmVudC50cy5PbmJvYXJkaW5nQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuICAiLCI8ZGV0YWlsPjwvZGV0YWlsPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsOENBQ0k7TUFBQTtNQUFBLGlFQUFBO01BQUE7VUFBQSxxRUFBK0I7YUFBQTtJQUEvQjs7OztvQkNESjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
