/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../src/app/pages/onboarding/welcome/welcome.component';
import * as i1 from './welcome.component.ngfactory';
export function OnboardingWelcomeComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.OnboardingWelcomeComponent,diDeps:([] as any[]),
      lifecycleHooks:[0]},isComponent:true,selector:'onboarding-welcome',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i1.View_OnboardingWelcomeComponent_0,
      rendererType:i1.RenderType_OnboardingWelcomeComponent,componentFactory:i1.OnboardingWelcomeComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL29uYm9hcmRpbmcvd2VsY29tZS93ZWxjb21lLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2dlcnRqYWFwL3NvdXJjZXMvZGVjb3MuY3J5cHRvLmVzaWduYXR1cmUvc3JjL2FwcC9wYWdlcy9vbmJvYXJkaW5nL3dlbGNvbWUvd2VsY29tZS5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
