/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../src/app/pages/onboarding/setwalletpassword/setwalletpassword.component';
import * as i1 from '../../../../../../src/app/services/wallet/wallet.service';
import * as i2 from '@angular/router';
import * as i3 from './setwalletpassword.component.ngfactory';
export function OnboardingSetWalletPasswordComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.OnboardingSetWalletPasswordComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.WalletService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.Router}}}],lifecycleHooks:[0]},isComponent:true,
      selector:'onboarding-setwalletpassword',exportAs:(null as any),inputs:{},outputs:{},
      hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i3.View_OnboardingSetWalletPasswordComponent_0,
      rendererType:i3.RenderType_OnboardingSetWalletPasswordComponent,componentFactory:i3.OnboardingSetWalletPasswordComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL29uYm9hcmRpbmcvc2V0d2FsbGV0cGFzc3dvcmQvc2V0d2FsbGV0cGFzc3dvcmQuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL29uYm9hcmRpbmcvc2V0d2FsbGV0cGFzc3dvcmQvc2V0d2FsbGV0cGFzc3dvcmQuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
