/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.module';
import * as i2 from '../../../src/app/app.component';
import * as i3 from './pages/onboarding/onboarding.component.ngfactory';
import * as i4 from './pages/home/home.component.ngfactory';
import * as i5 from './pages/addfunds/addfunds.component.ngfactory';
import * as i6 from './pages/signdocument/signdocument.component.ngfactory';
import * as i7 from './pages/onboarding/welcome/welcome.component.ngfactory';
import * as i8 from './pages/onboarding/newwallet/newwallet.component.ngfactory';
import * as i9 from './pages/onboarding/setwalletpassword/setwalletpassword.component.ngfactory';
import * as i10 from './app.component.ngfactory';
import * as i11 from '@angular/common';
import * as i12 from '@angular/platform-browser';
import * as i13 from '@angular/animations/browser';
import * as i14 from '@angular/platform-browser/animations';
import * as i15 from '@angular/animations';
import * as i16 from '@angular/forms';
import * as i17 from '@angular/http';
import * as i18 from '@angular/common/http';
import * as i19 from '@angular/router';
import * as i20 from '../../../src/app/services/wallet/wallet.service';
import * as i21 from '../../../src/app/services/blockchain/blockchain.service';
import * as i22 from '../../../src/app/services/document/document.service';
import * as i23 from '../../../src/app/pipes/numeral.pipe';
import * as i24 from '../../../src/app/pages/onboarding/onboarding.component';
import * as i25 from '../../../src/app/pages/home/home.component';
import * as i26 from '../../../src/app/pages/addfunds/addfunds.component';
import * as i27 from '../../../src/app/pages/signdocument/signdocument.component';
import * as i28 from '../../../src/app/pages/onboarding/welcome/welcome.component';
import * as i29 from '../../../src/app/pages/onboarding/newwallet/newwallet.component';
import * as i30 from '../../../src/app/pages/onboarding/setwalletpassword/setwalletpassword.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.OnboardingComponentNgFactory,i4.HomeComponentNgFactory,i5.AddFundsComponentNgFactory,
              i6.SignDocumentComponentNgFactory,i7.OnboardingWelcomeComponentNgFactory,
              i8.OnboardingNewWalletComponentNgFactory,i9.OnboardingSetWalletPasswordComponentNgFactory,
              i10.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i11.NgLocalization,
              i11.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i12.DomSanitizer,
              i12.ɵe,[i11.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i12.DomSanitizer]),
          i0.ɵmpd(4608,i12.HAMMER_GESTURE_CONFIG,i12.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i12.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i12.ɵDomEventsPlugin(p0_0),new i12.ɵKeyEventsPlugin(p1_0),
                new i12.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i11.DOCUMENT,i11.DOCUMENT,i11.DOCUMENT,i12.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i12.EventManager,i12.EventManager,[i12.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i12.ɵDomSharedStylesHost,i12.ɵDomSharedStylesHost,[i11.DOCUMENT]),
          i0.ɵmpd(4608,i12.ɵDomRendererFactory2,i12.ɵDomRendererFactory2,[i12.EventManager,
              i12.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i13.AnimationDriver,i14.ɵc,([] as any[])),
          i0.ɵmpd(5120,i13.ɵAnimationStyleNormalizer,i14.ɵd,([] as any[])),i0.ɵmpd(4608,
              i13.ɵAnimationEngine,i14.ɵb,[i13.AnimationDriver,i13.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i14.ɵe,[i12.ɵDomRendererFactory2,i13.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i12.ɵSharedStylesHost,(null as any),[i12.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i12.Meta,
              i12.Meta,[i11.DOCUMENT]),i0.ɵmpd(4608,i12.Title,i12.Title,[i11.DOCUMENT]),
          i0.ɵmpd(4608,i15.AnimationBuilder,i14.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
              i12.DOCUMENT]),i0.ɵmpd(4608,i16.ɵi,i16.ɵi,([] as any[])),i0.ɵmpd(4608,
              i17.BrowserXhr,i17.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i17.ResponseOptions,
              i17.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i17.XSRFStrategy,
              i17.ɵb,([] as any[])),i0.ɵmpd(4608,i17.XHRBackend,i17.XHRBackend,[i17.BrowserXhr,
              i17.ResponseOptions,i17.XSRFStrategy]),i0.ɵmpd(4608,i17.RequestOptions,
              i17.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i17.Http,i17.ɵc,[i17.XHRBackend,
              i17.RequestOptions]),i0.ɵmpd(4608,i18.HttpXsrfTokenExtractor,i18.ɵg,
              [i11.DOCUMENT,i0.PLATFORM_ID,i18.ɵe]),i0.ɵmpd(4608,i18.ɵh,i18.ɵh,[i18.HttpXsrfTokenExtractor,
              i18.ɵf]),i0.ɵmpd(5120,i18.HTTP_INTERCEPTORS,(p0_0:any) => {
            return [p0_0];
          },[i18.ɵh]),i0.ɵmpd(4608,i18.ɵd,i18.ɵd,([] as any[])),i0.ɵmpd(6144,i18.XhrFactory,
              (null as any),[i18.ɵd]),i0.ɵmpd(4608,i18.HttpXhrBackend,i18.HttpXhrBackend,
              [i18.XhrFactory]),i0.ɵmpd(6144,i18.HttpBackend,(null as any),[i18.HttpXhrBackend]),
          i0.ɵmpd(5120,i18.HttpHandler,i18.ɵinterceptingHandler,[i18.HttpBackend,[2,
              i18.HTTP_INTERCEPTORS]]),i0.ɵmpd(4608,i18.HttpClient,i18.HttpClient,
              [i18.HttpHandler]),i0.ɵmpd(5120,i19.ActivatedRoute,i19.ɵf,[i19.Router]),
          i0.ɵmpd(4608,i19.PreloadAllModules,i19.PreloadAllModules,([] as any[])),
          i0.ɵmpd(6144,i19.PreloadingStrategy,(null as any),[i19.PreloadAllModules]),
          i0.ɵmpd(135680,i19.RouterPreloader,i19.RouterPreloader,[i19.Router,i0.NgModuleFactoryLoader,
              i0.Compiler,i0.Injector,i19.PreloadingStrategy]),i0.ɵmpd(4608,i19.NoPreloading,
              i19.NoPreloading,([] as any[])),i0.ɵmpd(5120,i19.ROUTER_INITIALIZER,
              i19.ɵi,[i19.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i19.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i20.WalletService,i20.WalletService,
              [i0.NgZone]),i0.ɵmpd(4608,i21.BlockchainService,i21.BlockchainService,
              [i20.WalletService,i18.HttpClient]),i0.ɵmpd(4608,i22.DocumentService,
              i22.DocumentService,[i20.WalletService]),i0.ɵmpd(4608,i23.NumeralPipe,
              i23.NumeralPipe,([] as any[])),i0.ɵmpd(512,i11.CommonModule,i11.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i12.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i19.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i19.ɵg,i19.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i12.ɵc(p0_0,p0_1),i19.ɵh(p1_0)];
              },[[2,i12.NgProbeToken],[2,i0.NgProbeToken],i19.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i12.BrowserModule,i12.BrowserModule,[[3,i12.BrowserModule]]),
          i0.ɵmpd(512,i14.BrowserAnimationsModule,i14.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i16.ɵba,i16.ɵba,([] as any[])),i0.ɵmpd(512,i16.FormsModule,i16.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i17.HttpModule,i17.HttpModule,([] as any[])),
          i0.ɵmpd(1024,i19.ɵa,i19.ɵd,[[3,i19.Router]]),i0.ɵmpd(512,i19.UrlSerializer,
              i19.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i19.ChildrenOutletContexts,
              i19.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i19.ROUTER_CONFIGURATION,
              {preloadingStrategy:i19.PreloadAllModules},([] as any[])),i0.ɵmpd(1024,
              i11.LocationStrategy,i19.ɵc,[i11.PlatformLocation,[2,i11.APP_BASE_HREF],
                  i19.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i11.Location,i11.Location,
              [i11.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),
          i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,[i0.Compiler,
              [2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i19.ROUTES,() => {
            return [[{path:'',component:i24.OnboardingComponent},{path:'home',component:i25.HomeComponent},
                {path:'addfunds',component:i26.AddFundsComponent},{path:'signdocument',
                    component:i27.SignDocumentComponent},{path:'onboarding',component:i24.OnboardingComponent,
                    children:[{path:'welcome',component:i28.OnboardingWelcomeComponent},
                        {path:'newwallet',component:i29.OnboardingNewWalletComponent},
                        {path:'setwalletpassword',component:i30.OnboardingSetWalletPasswordComponent}]}]];
          },([] as any[])),i0.ɵmpd(1024,i19.Router,i19.ɵe,[i0.ApplicationRef,i19.UrlSerializer,
              i19.ChildrenOutletContexts,i11.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i19.ROUTES,i19.ROUTER_CONFIGURATION,[2,i19.UrlHandlingStrategy],
              [2,i19.RouteReuseStrategy]]),i0.ɵmpd(512,i19.RouterModule,i19.RouterModule,
              [[2,i19.ɵa],[2,i19.Router]]),i0.ɵmpd(512,i18.HttpClientXsrfModule,i18.HttpClientXsrfModule,
              ([] as any[])),i0.ɵmpd(512,i18.HttpClientModule,i18.HttpClientModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),
          i0.ɵmpd(256,i18.ɵe,'XSRF-TOKEN',([] as any[])),i0.ɵmpd(256,i18.ɵf,'X-XSRF-TOKEN',
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9nZXJ0amFhcC9zb3VyY2VzL2RlY29zLmNyeXB0by5lc2lnbmF0dXJlL3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
