/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/pages/home/home.component';
import * as i1 from './home.component.ngfactory';
export function HomeComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.HomeComponent,diDeps:([] as any[]),lifecycleHooks:[0]},
      isComponent:true,selector:'home',exportAs:(null as any),inputs:{},outputs:{},
      hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i1.View_HomeComponent_0,rendererType:i1.RenderType_HomeComponent,
      componentFactory:i1.HomeComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL2hvbWUvaG9tZS5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9nZXJ0amFhcC9zb3VyY2VzL2RlY29zLmNyeXB0by5lc2lnbmF0dXJlL3NyYy9hcHAvcGFnZXMvaG9tZS9ob21lLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
