/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './home.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from '../../../../../src/app/pages/home/home.component';
const styles_HomeComponent:any[] = [i0.styles];
export const RenderType_HomeComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_HomeComponent,data:{}});
export function View_HomeComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),12,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n    '])),(_l()(),i1.ɵeld(2,0,(null as any),(null as any),
      9,'div',[['class','row']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n        '])),(_l()(),i1.ɵeld(4,
      0,(null as any),(null as any),6,'div',[['class','col-lg-6 col-md-12']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵeld(5,
      0,(null as any),(null as any),5,'button',[['class','btn walletChoiceButton']],
      (null as any),[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,6).onClick()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(6,16384,(null as any),0,i2.RouterLink,
      [i2.Router,i2.ActivatedRoute,[8,(null as any)],i1.Renderer2,i1.ElementRef],{routerLink:[0,
          'routerLink']},(null as any)),i1.ɵpad(7,1),(_l()(),i1.ɵeld(8,0,(null as any),
      (null as any),0,'i',[['class','fa fa-pencil-square']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵeld(9,0,(null as any),
      (null as any),0,'br',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['Sign a document'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n      '])),(_l()(),i1.ɵted(-1,(null as any),
          ['\n'])),(_l()(),i1.ɵted(-1,(null as any),['\n']))],(_ck,_v) => {
    const currVal_0:any = _ck(_v,7,0,'/signdocument');
    _ck(_v,6,0,currVal_0);
  },(null as any));
}
export function View_HomeComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'home',([] as any[]),
      (null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
      i1.ɵdid(1,114688,(null as any),0,i3.HomeComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const HomeComponentNgFactory:i1.ComponentFactory<i3.HomeComponent> = i1.ɵccf('home',
    i3.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL2hvbWUvaG9tZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9nZXJ0amFhcC9zb3VyY2VzL2RlY29zLmNyeXB0by5lc2lnbmF0dXJlL3NyYy9hcHAvcGFnZXMvaG9tZS9ob21lLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL2hvbWUvaG9tZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL2hvbWUvaG9tZS5jb21wb25lbnQudHMuSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLWxnLTYgY29sLW1kLTEyXCI+PGJ1dHRvbiBjbGFzcz1cImJ0biB3YWxsZXRDaG9pY2VCdXR0b25cIiBbcm91dGVyTGlua109XCIgWycvc2lnbmRvY3VtZW50J10gXCI+PGkgY2xhc3M9XCJmYSBmYS1wZW5jaWwtc3F1YXJlXCI+PC9pPjxici8+U2lnbiBhIGRvY3VtZW50PC9idXR0b24+PC9kaXY+XG4gICAgICA8L2Rpdj5cbjwvZGl2PlxuIiwiPGhvbWU+PC9ob21lPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSzthQUFBLCtCQUNEO01BQUE7TUFBQSxnQkFBaUIsa0RBQ2I7TUFBQTtNQUFBLDBEQUFnQztNQUFBO01BQUE7UUFBQTtRQUFBO1VBQUE7VUFBQTtRQUFBO1FBQUE7TUFBQSx1Q0FBQTtNQUFBO1VBQUEscUNBQXVDLE1BQW1DO01BQUE7TUFBQSw0Q0FBbUM7TUFBQTtNQUFBLDhCQUFLO01BQThCLGdEQUM1SztVQUFBLFNBQ047SUFGeUU7SUFBdkMsV0FBdUMsU0FBdkM7Ozs7b0JDRnhDO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7In0=
