/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/pipes/numeral.pipe';
export function NumeralPipeNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.NumeralPipe,diDeps:([] as any[]),lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BpcGVzL251bWVyYWwucGlwZS5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2dlcnRqYWFwL3NvdXJjZXMvZGVjb3MuY3J5cHRvLmVzaWduYXR1cmUvc3JjL2FwcC9waXBlcy9udW1lcmFsLnBpcGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7OyJ9
