/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../src/app/pages/onboarding/newwallet/newwallet.component';
import * as i1 from '../../../../../../src/app/services/wallet/wallet.service';
import * as i2 from './newwallet.component.ngfactory';
export function OnboardingNewWalletComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.OnboardingNewWalletComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.WalletService}}}],
      lifecycleHooks:[0]},isComponent:true,selector:'onboarding-newwallet',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i2.View_OnboardingNewWalletComponent_0,
      rendererType:i2.RenderType_OnboardingNewWalletComponent,componentFactory:i2.OnboardingNewWalletComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL29uYm9hcmRpbmcvbmV3d2FsbGV0L25ld3dhbGxldC5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9nZXJ0amFhcC9zb3VyY2VzL2RlY29zLmNyeXB0by5lc2lnbmF0dXJlL3NyYy9hcHAvcGFnZXMvb25ib2FyZGluZy9uZXd3YWxsZXQvbmV3d2FsbGV0LmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
