/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['div.recoverySeed[_ngcontent-%COMP%]{margin:30px;height:60px;font-size:12pt;font-family:Courier New,Courier,monospace;background-color:#e0e0e0;line-height:40px;text-align:center;padding:10px}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL29uYm9hcmRpbmcvbmV3d2FsbGV0L25ld3dhbGxldC5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2dlcnRqYWFwL3NvdXJjZXMvZGVjb3MuY3J5cHRvLmVzaWduYXR1cmUvc3JjL2FwcC9wYWdlcy9vbmJvYXJkaW5nL25ld3dhbGxldC9uZXd3YWxsZXQuY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
