/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/pages/addfunds/addfunds.component';
import * as i1 from '../../../../../src/app/services/wallet/wallet.service';
import * as i2 from './addfunds.component.ngfactory';
export function AddFundsComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.AddFundsComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.WalletService}}}],
      lifecycleHooks:[0]},isComponent:true,selector:'addfunds',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i2.View_AddFundsComponent_0,rendererType:i2.RenderType_AddFundsComponent,
      componentFactory:i2.AddFundsComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL2FkZGZ1bmRzL2FkZGZ1bmRzLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2dlcnRqYWFwL3NvdXJjZXMvZGVjb3MuY3J5cHRvLmVzaWduYXR1cmUvc3JjL2FwcC9wYWdlcy9hZGRmdW5kcy9hZGRmdW5kcy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
