/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './addfunds.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../src/app/pages/addfunds/addfunds.component';
import * as i3 from '../../../../../src/app/services/wallet/wallet.service';
const styles_AddFundsComponent:any[] = [i0.styles];
export const RenderType_AddFundsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AddFundsComponent,data:{}});
export function View_AddFundsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),10,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵeld(2,0,(null as any),(null as any),
      1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['Add funds'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n  '])),(_l()(),i1.ɵeld(5,0,(null as any),(null as any),1,'p',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['You can add funds to this wallet by sending VTC to the following address:'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵeld(8,0,(null as any),
          (null as any),1,'div',[['class','walletAddress']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(9,(null as any),
          ['',''])),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵted(-1,(null as any),
          ['\n']))],(null as any),(_ck,_v) => {
    var _co:i2.AddFundsComponent = _v.component;
    const currVal_0:any = _co.address;
    _ck(_v,9,0,currVal_0);
  });
}
export function View_AddFundsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'addfunds',([] as any[]),
      (null as any),(null as any),(null as any),View_AddFundsComponent_0,RenderType_AddFundsComponent)),
      i1.ɵdid(1,114688,(null as any),0,i2.AddFundsComponent,[i3.WalletService],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AddFundsComponentNgFactory:i1.ComponentFactory<i2.AddFundsComponent> = i1.ɵccf('addfunds',
    i2.AddFundsComponent,View_AddFundsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL2FkZGZ1bmRzL2FkZGZ1bmRzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2dlcnRqYWFwL3NvdXJjZXMvZGVjb3MuY3J5cHRvLmVzaWduYXR1cmUvc3JjL2FwcC9wYWdlcy9hZGRmdW5kcy9hZGRmdW5kcy5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL2dlcnRqYWFwL3NvdXJjZXMvZGVjb3MuY3J5cHRvLmVzaWduYXR1cmUvc3JjL2FwcC9wYWdlcy9hZGRmdW5kcy9hZGRmdW5kcy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3BhZ2VzL2FkZGZ1bmRzL2FkZGZ1bmRzLmNvbXBvbmVudC50cy5BZGRGdW5kc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXY+XG4gIDxoMT5BZGQgZnVuZHM8L2gxPlxuICA8cD5Zb3UgY2FuIGFkZCBmdW5kcyB0byB0aGlzIHdhbGxldCBieSBzZW5kaW5nIFZUQyB0byB0aGUgZm9sbG93aW5nIGFkZHJlc3M6PC9wPlxuICA8ZGl2IGNsYXNzPVwid2FsbGV0QWRkcmVzc1wiPnt7YWRkcmVzc319PC9kaXY+XG48L2Rpdj5cbiIsIjxhZGRmdW5kcz48L2FkZGZ1bmRzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSzthQUFBLDZCQUNIO01BQUE7TUFBQSxnQkFBSSxpREFBYztNQUFBLHlCQUNsQjtNQUFBO01BQUc7TUFBNkUsNENBQ2hGO1VBQUE7VUFBQSw0Q0FBMkI7VUFBQSxVQUFpQiwwQ0FDeEM7VUFBQTs7SUFEdUI7SUFBQTs7OztvQkNIN0I7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
