/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/services/wallet/wallet.service';
import * as i1 from '@angular/core';
export function WalletServiceNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.WalletService,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.NgZone}}}],
      lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2VydGphYXAvc291cmNlcy9kZWNvcy5jcnlwdG8uZXNpZ25hdHVyZS9zcmMvYXBwL3NlcnZpY2VzL3dhbGxldC93YWxsZXQuc2VydmljZS5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2dlcnRqYWFwL3NvdXJjZXMvZGVjb3MuY3J5cHRvLmVzaWduYXR1cmUvc3JjL2FwcC9zZXJ2aWNlcy93YWxsZXQvd2FsbGV0LnNlcnZpY2UudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OyJ9
